name: 'Gitbook-Action'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v1

    # example1
    - name: Gitbook Action
      uses: zanderzhao/gitbook-action@v1.2.2
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        time_zone: Asia/Shanghai
        publish_commit_message: ${{ github.event.head_commit.message }}
